[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
skip-string-normalization = true
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.env
  | \.env353
  | \.env386
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
